// English names of the countries in countries.ts, by code (the table there holds the Russian ones).
export const COUNTRY_NAMES_EN: Readonly<Record<string, string>> = {
  AU: 'Australia', AT: 'Austria', AZ: 'Azerbaijan', AL: 'Albania', DZ: 'Algeria', AS: 'American Samoa', AO: 'Angola',
  AD: 'Andorra', AG: 'Antigua & Barbuda', AR: 'Argentina', AM: 'Armenia', AW: 'Aruba', AF: 'Afghanistan', BS: 'Bahamas',
  BD: 'Bangladesh', BB: 'Barbados', BH: 'Bahrain', BY: 'Belarus', BZ: 'Belize', BE: 'Belgium', BJ: 'Benin', BM: 'Bermuda',
  BG: 'Bulgaria', BO: 'Bolivia', BA: 'Bosnia & Herzegovina', BW: 'Botswana', BR: 'Brazil', BN: 'Brunei', BF: 'Burkina Faso',
  BI: 'Burundi', BT: 'Bhutan', VU: 'Vanuatu', VA: 'Vatican City', GB: 'United Kingdom', HU: 'Hungary', VE: 'Venezuela',
  VG: 'British Virgin Islands', VI: 'U.S. Virgin Islands', TL: 'Timor-Leste', VN: 'Vietnam', GA: 'Gabon', HT: 'Haiti',
  GY: 'Guyana', GM: 'Gambia', GH: 'Ghana', GT: 'Guatemala', GN: 'Guinea', GW: 'Guinea-Bissau', DE: 'Germany',
  GI: 'Gibraltar', HN: 'Honduras', HK: 'Hong Kong SAR China', GD: 'Grenada', GL: 'Greenland', GR: 'Greece', GE: 'Georgia',
  GU: 'Guam', DK: 'Denmark', DJ: 'Djibouti', DM: 'Dominica', DO: 'Dominican Republic', EG: 'Egypt', ZM: 'Zambia',
  ZW: 'Zimbabwe', IL: 'Israel', IN: 'India', ID: 'Indonesia', JO: 'Jordan', IQ: 'Iraq', IR: 'Iran', IE: 'Ireland',
  IS: 'Iceland', ES: 'Spain', IT: 'Italy', YE: 'Yemen', CV: 'Cape Verde', KZ: 'Kazakhstan', KH: 'Cambodia', CM: 'Cameroon',
  CA: 'Canada', QA: 'Qatar', KE: 'Kenya', CY: 'Cyprus', KG: 'Kyrgyzstan', KI: 'Kiribati', CN: 'China', KP: 'North Korea',
  CO: 'Colombia', KM: 'Comoros', CG: 'Congo - Brazzaville', CD: 'Congo - Kinshasa', XK: 'Kosovo', CR: 'Costa Rica',
  CI: 'Côte d’Ivoire', CU: 'Cuba', KW: 'Kuwait', CW: 'Curaçao', LA: 'Laos', LV: 'Latvia', LS: 'Lesotho', LR: 'Liberia',
  LB: 'Lebanon', LY: 'Libya', LT: 'Lithuania', LI: 'Liechtenstein', LU: 'Luxembourg', MU: 'Mauritius', MR: 'Mauritania',
  MG: 'Madagascar', MO: 'Macao SAR China', MW: 'Malawi', MY: 'Malaysia', ML: 'Mali', MV: 'Maldives', MT: 'Malta',
  MA: 'Morocco', MH: 'Marshall Islands', MX: 'Mexico', MZ: 'Mozambique', MD: 'Moldova', MC: 'Monaco', MN: 'Mongolia',
  MM: 'Myanmar (Burma)', NA: 'Namibia', NR: 'Nauru', NP: 'Nepal', NE: 'Niger', NG: 'Nigeria', NL: 'Netherlands',
  NI: 'Nicaragua', NZ: 'New Zealand', NC: 'New Caledonia', NO: 'Norway', IM: 'Isle of Man', KY: 'Cayman Islands',
  AE: 'United Arab Emirates', OM: 'Oman', PK: 'Pakistan', PW: 'Palau', PS: 'Palestinian Territories', PA: 'Panama',
  PG: 'Papua New Guinea', PY: 'Paraguay', PE: 'Peru', PL: 'Poland', PT: 'Portugal', PR: 'Puerto Rico', KR: 'South Korea',
  RU: 'Russia', RW: 'Rwanda', RO: 'Romania', SV: 'El Salvador', WS: 'Samoa', SM: 'San Marino', ST: 'São Tomé & Príncipe',
  SA: 'Saudi Arabia', MK: 'North Macedonia', MP: 'Northern Mariana Islands', SC: 'Seychelles', MF: 'St. Martin',
  SN: 'Senegal', VC: 'St. Vincent & Grenadines', KN: 'St. Kitts & Nevis', LC: 'St. Lucia', RS: 'Serbia', SG: 'Singapore',
  SX: 'Sint Maarten', SY: 'Syria', SK: 'Slovakia', SI: 'Slovenia', US: 'United States', SB: 'Solomon Islands',
  SO: 'Somalia', SD: 'Sudan', SR: 'Suriname', SL: 'Sierra Leone', TJ: 'Tajikistan', TH: 'Thailand', TW: 'Taiwan',
  TZ: 'Tanzania', TC: 'Turks & Caicos Islands', TG: 'Togo', TO: 'Tonga', TT: 'Trinidad & Tobago', TV: 'Tuvalu',
  TN: 'Tunisia', TM: 'Turkmenistan', TR: 'Türkiye', UG: 'Uganda', UZ: 'Uzbekistan', UA: 'Ukraine', UY: 'Uruguay',
  FO: 'Faroe Islands', FM: 'Micronesia', FJ: 'Fiji', PH: 'Philippines', FI: 'Finland', FR: 'France', PF: 'French Polynesia',
  HR: 'Croatia', CF: 'Central African Republic', TD: 'Chad', ME: 'Montenegro', CZ: 'Czechia', CL: 'Chile', CH: 'Switzerland',
  SE: 'Sweden', LK: 'Sri Lanka', EC: 'Ecuador', GQ: 'Equatorial Guinea', ER: 'Eritrea', SZ: 'Eswatini', EE: 'Estonia',
  ET: 'Ethiopia', ZA: 'South Africa', SS: 'South Sudan', JM: 'Jamaica', JP: 'Japan',
};
